name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Delete components
      run: |
              Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
              $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
              $componentsToRemove= @(
                "Microsoft.VisualStudio.Component.VC.ATL"
                "Microsoft.VisualStudio.Component.VC.ATL.Spectre"
                "Microsoft.VisualStudio.Component.VC.ATLMFC"
                "Microsoft.VisualStudio.Component.VC.ATLMFC.Spectre"
              )
              [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --remove " +  $_}
              $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
              # should be run twice
              $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
              $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
      
    - name: Install components
      run: |
              Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
              $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
              $componentsToAdd= @(
                "Microsoft.VisualStudio.Component.VC.14.29.16.11.ATL"
                "Microsoft.VisualStudio.Component.VC.14.29.16.11.ATL.Spectre"
                "Microsoft.VisualStudio.Component.VC.14.29.16.11.MFC"
                "Microsoft.VisualStudio.Component.VC.14.29.16.11.MFC.Spectre"
              )
              [string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
              $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
              # should be run twice
              $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
              $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden

    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64

    - name: build
      shell: cmd
      run: |
        cd libraries/funchook
        mkdir build
        cd build
        cmake -T v142 ..
        cmake --build . --config release
        cd ../../..
        msbuild -p:configuration=release -p:platform=x64 awm.sln
        
    - uses: actions/upload-artifact@v4
      with:
        name: awm
        path: |
            x64/*
            
